apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 8
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: DOCKER_REGISTRY/worker:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
